disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - for_where
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - opening_brace
  - trailing_comma
  - type_body_length

excluded:
  - .build
  - _bmad-output/ml-training/swift_feature_extractor/.build
  - tools/coreml-convert/.venv
  - _bmad-output/ml-training/.venv
